

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jirucho
 */

public class Pookimuni extends javax.swing.JFrame {

    /**
     * Creates new form Pookimuni
     */
    public Pookimuni() {
        initComponents();
        fin.setVisible(false);
        v_vida1.setValue(50);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        curav.setVisible(false);
        curau.setVisible(false);
//Elige el turno al azar al inicio
        double turn = Math.random()*2;
        if((int)turn==0){
            
            turno.setText("Valkyria");
             jButton1.setVisible(true);
            curav.setVisible(true);
        }else if((int)turn==1){
            turno.setText("Unicornio");
        jButton2.setVisible(true);
            curau.setVisible(true);
        }
        
      
    }
  
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fin = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        u_vida1 = new javax.swing.JProgressBar();
        curav = new javax.swing.JButton();
        curau = new javax.swing.JButton();
        valk1 = new javax.swing.JLabel();
        valk = new javax.swing.JLabel();
        uni1 = new javax.swing.JLabel();
        v_vida1 = new javax.swing.JProgressBar();
        v_vida = new javax.swing.JProgressBar();
        u_vida = new javax.swing.JProgressBar();
        uni = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1180, 570));
        getContentPane().setLayout(null);

        fin.setBackground(new java.awt.Color(51, 0, 51));
        fin.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 36)); // NOI18N
        fin.setOpaque(true);
        getContentPane().add(fin);
        fin.setBounds(0, 0, 1170, 580);

        turno.setBackground(new java.awt.Color(0, 255, 0));
        turno.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        turno.setOpaque(true);
        getContentPane().add(turno);
        turno.setBounds(570, 40, 80, 30);

        jLabel7.setBackground(new java.awt.Color(0, 255, 0));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Turno de ");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 40, 80, 30);

        u_vida1.setMaximum(50);
        u_vida1.setValue(50);
        getContentPane().add(u_vida1);
        u_vida1.setBounds(910, 340, 220, 20);

        curav.setText("Curacion");
        curav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curavMousePressed(evt);
            }
        });
        getContentPane().add(curav);
        curav.setBounds(40, 340, 100, 20);

        curau.setText("Curacion");
        curau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curauMousePressed(evt);
            }
        });
        getContentPane().add(curau);
        curau.setBounds(1030, 370, 100, 20);

        valk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/League-of-Legends-Red-Minion1.png"))); // NOI18N
        getContentPane().add(valk1);
        valk1.setBounds(60, 350, 240, 230);

        valk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PieceValkiriabltG.png"))); // NOI18N
        valk.setMaximumSize(new java.awt.Dimension(200, 200));
        valk.setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().add(valk);
        valk.setBounds(130, 140, 320, 390);

        uni1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Subdito_hechicero.png"))); // NOI18N
        getContentPane().add(uni1);
        uni1.setBounds(890, 340, 190, 190);

        v_vida1.setMaximum(50);
        v_vida1.setValue(50);
        getContentPane().add(v_vida1);
        v_vida1.setBounds(0, 360, 220, 20);

        v_vida.setValue(100);
        getContentPane().add(v_vida);
        v_vida.setBounds(107, 31, 292, 46);

        u_vida.setValue(100);
        getContentPane().add(u_vida);
        u_vida.setBounds(693, 28, 306, 46);

        uni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PieceUnicornbltG.png"))); // NOI18N
        getContentPane().add(uni);
        uni.setBounds(650, 100, 400, 400);

        jButton1.setText("<Ataque>");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(434, 187, 83, 23);

        jButton2.setText("<Ataque>");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 230, 83, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FFIV_PSP_Final_Dungeon_Background_2.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(1280, 713));
        jLabel3.setMinimumSize(new java.awt.Dimension(1280, 713));
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 713));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1140, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        //While para que la valkyria no ataque una vez llege a perder o NO sea su Turno
       
        while(v_vida.getValue()>0 && turno.getText().equals("Valkyria")){
            //Ataque al azar entre 30~15
     double random = (Math.random()*30)+15;
     double random2 = Math.random()*2;
     //Elige al azar cual de los dos atacar
     if((int)random2==0){
     int nueva_vida = u_vida.getValue()-(int)random;
     u_vida.setValue(nueva_vida);
     }else if((int)random2==1){
     int nueva_vida = u_vida1.getValue()-(int)random;
     u_vida1.setValue(nueva_vida);
     }
     jButton1.setVisible(false);
            curav.setVisible(false);
     if(u_vida.getValue()<=0){
         uni.setVisible(false);
         u_vida.setVisible(false);
     }if(u_vida1.getValue()<=0){
         uni1.setVisible(false);
         u_vida1.setVisible(false);
     }if(u_vida.getValue()<=0 && u_vida1.getValue()<=0){
         //EN CASO DE NO PODER CONTINUAR AMBOS MARCA LA VICTORIA PARA LA VALKYRIA
         turno.setText("");
         fin.setVisible(true);
         fin.setText("VALKYRIA WINS");
         
     }
         //Cambia el turno de un equipo al otro
         turno.setText("Unicornio");
          jButton2.setVisible(true);
            curau.setVisible(true);
         
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
         //While para que unicornio no ataque una vez llege a perder
        while(u_vida.getValue()>0 && turno.getText().equals("Unicornio")){
    double random = (Math.random()*30)+15;
     double random2 = Math.random()*2;
     if((int)random2==0){
     int nueva_vida = v_vida.getValue()-(int)random;
     v_vida.setValue(nueva_vida);
     }else if((int)random2==1){
     int nueva_vida = v_vida1.getValue()-(int)random;
     v_vida1.setValue(nueva_vida);
     }
     
     jButton2.setVisible(false);
            curau.setVisible(false);
     if(v_vida.getValue()<=0){
        valk.setVisible(false);
         v_vida.setVisible(false);  
          }if(v_vida1.getValue()<=0){
         valk1.setVisible(false);
         v_vida1.setVisible(false);
    }
          if(v_vida.getValue()<=0 && v_vida1.getValue()<=0){
              //EN CASO DE NO PODER CONTINUAR AMBOS MARCA LA VICTORIA PARA LA VALKYRIA

         turno.setText("");
         fin.setVisible(true);
         fin.setText("UNICORNIO WINS");
        
          }
         turno.setText("Valkyria");
          jButton1.setVisible(true);
            curav.setVisible(true);
         
     }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void curavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curavMousePressed
         // EVITA QUE EL MISMO SE CURE FUERA DE TURNO O EN CASO DE PERDER
        while(v_vida1.getValue()>0 && turno.getText().equals("Valkyria")){
     int vidav = v_vida.getValue();
     int vidam1 = v_vida1.getValue();
     
     
     if(vidav>0){
         vidav+= 10;
         v_vida.setValue(vidav);
     }
     if(vidam1>0){
         vidam1+=5;
     v_vida1.setValue(vidam1);
     
     }
       jButton1.setVisible(false);
            curav.setVisible(false);
         turno.setText("Unicornio");
          jButton2.setVisible(true);
            curau.setVisible(true);
         }
// TODO add your handling code here:
    }//GEN-LAST:event_curavMousePressed

    private void curauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curauMousePressed
        
        while(u_vida1.getValue()>0&& turno.getText().equals("Unicornio")){
        int vidau = u_vida.getValue();
     int vidam1 = u_vida1.getValue();
     
    
     if(vidau>0){
         vidau+= 10;
         u_vida.setValue(vidau);
     }
     if(vidam1>0){
          vidam1+=5;
     u_vida1.setValue(vidam1);
     }
       jButton2.setVisible(false);
            curau.setVisible(false);
        turno.setText("Valkyria");
        jButton1.setVisible(true);
            curav.setVisible(true);}  // TODO add your handling code here:
    }//GEN-LAST:event_curauMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pookimuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pookimuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pookimuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pookimuni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pookimuni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton curau;
    private javax.swing.JButton curav;
    private javax.swing.JLabel fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel turno;
    private javax.swing.JProgressBar u_vida;
    private javax.swing.JProgressBar u_vida1;
    private javax.swing.JLabel uni;
    private javax.swing.JLabel uni1;
    private javax.swing.JProgressBar v_vida;
    private javax.swing.JProgressBar v_vida1;
    private javax.swing.JLabel valk;
    private javax.swing.JLabel valk1;
    // End of variables declaration//GEN-END:variables
}
